/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as EscanearRouteImport } from './routes/escanear'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as FichaRouteImport } from './routes/ficha'
import { Route as IdentificadoRouteImport } from './routes/identificado'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as ApiPublicCronTrendingRouteImport } from './routes/api/public/cron/trending'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const EscanearRoute = EscanearRouteImport.update({
  id: '/escanear',
  path: '/escanear',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const FichaRoute = FichaRouteImport.update({
  id: '/ficha',
  path: '/ficha',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentificadoRoute = IdentificadoRouteImport.update({
  id: '/identificado',
  path: '/identificado',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronTrendingRoute = ApiPublicCronTrendingRouteImport.update({
  id: '/api/public/cron/trending',
  path: '/api/public/cron/trending',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/buscar': typeof BuscarRoute
  '/escanear': typeof EscanearRoute
  '/favoritos': typeof FavoritosRoute
  '/ficha': typeof FichaRoute
  '/identificado': typeof IdentificadoRoute
  '/sobre': typeof SobreRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/api/public/cron/trending': typeof ApiPublicCronTrendingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/buscar': typeof BuscarRoute
  '/escanear': typeof EscanearRoute
  '/favoritos': typeof FavoritosRoute
  '/ficha': typeof FichaRoute
  '/identificado': typeof IdentificadoRoute
  '/sobre': typeof SobreRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/api/public/cron/trending': typeof ApiPublicCronTrendingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/buscar': typeof BuscarRoute
  '/escanear': typeof EscanearRoute
  '/favoritos': typeof FavoritosRoute
  '/ficha': typeof FichaRoute
  '/identificado': typeof IdentificadoRoute
  '/sobre': typeof SobreRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/api/public/cron/trending': typeof ApiPublicCronTrendingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/buscar'
    | '/escanear'
    | '/favoritos'
    | '/ficha'
    | '/identificado'
    | '/sobre'
    | '/produto/$id'
    | '/api/public/cron/trending'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/buscar'
    | '/escanear'
    | '/favoritos'
    | '/ficha'
    | '/identificado'
    | '/sobre'
    | '/produto/$id'
    | '/api/public/cron/trending'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/buscar'
    | '/escanear'
    | '/favoritos'
    | '/ficha'
    | '/identificado'
    | '/sobre'
    | '/produto/$id'
    | '/api/public/cron/trending'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BuscarRoute: typeof BuscarRoute
  EscanearRoute: typeof EscanearRoute
  FavoritosRoute: typeof FavoritosRoute
  FichaRoute: typeof FichaRoute
  IdentificadoRoute: typeof IdentificadoRoute
  SobreRoute: typeof SobreRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
  ApiPublicCronTrendingRoute: typeof ApiPublicCronTrendingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escanear': {
      id: '/escanear'
      path: '/escanear'
      fullPath: '/escanear'
      preLoaderRoute: typeof EscanearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ficha': {
      id: '/ficha'
      path: '/ficha'
      fullPath: '/ficha'
      preLoaderRoute: typeof FichaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identificado': {
      id: '/identificado'
      path: '/identificado'
      fullPath: '/identificado'
      preLoaderRoute: typeof IdentificadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/trending': {
      id: '/api/public/cron/trending'
      path: '/api/public/cron/trending'
      fullPath: '/api/public/cron/trending'
      preLoaderRoute: typeof ApiPublicCronTrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BuscarRoute: BuscarRoute,
  EscanearRoute: EscanearRoute,
  FavoritosRoute: FavoritosRoute,
  FichaRoute: FichaRoute,
  IdentificadoRoute: IdentificadoRoute,
  SobreRoute: SobreRoute,
  ProdutoIdRoute: ProdutoIdRoute,
  ApiPublicCronTrendingRoute: ApiPublicCronTrendingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
